// Product catalogue — edit this array to add, remove, or change products.
// Replace placeholder image paths with your real product photos when ready.
const PRODUCTS = [
  { id: 1, name: 'VoltX 20W Fast Charger', category: 'Mobile Accessories', price: 499, oldPrice: 699, badge: 'Best Seller', rating: 4.8, reviews: 126, image: 'images/product-01.svg', description: 'Compact 20W fast charger for phones, tablets and everyday devices.', features: ['20W fast charging', 'USB-C output', 'Compact travel design', 'Safety protection'] },
  { id: 2, name: 'FlexiCharge Type-C Cable', category: 'Mobile Accessories', price: 249, oldPrice: 349, badge: 'Deal', rating: 4.6, reviews: 89, image: 'images/product-02.svg', description: 'Durable braided Type-C cable designed for daily charging and data transfer.', features: ['1.5m length', 'Braided exterior', 'Fast-charge ready', 'Tangle resistant'] },
  { id: 3, name: 'AeroPods Lite Wireless Earbuds', category: 'Audio', price: 1299, oldPrice: 1799, badge: 'Popular', rating: 4.7, reviews: 214, image: 'images/product-03.svg', description: 'Lightweight wireless earbuds with a clean sound profile and pocket charging case.', features: ['Bluetooth 5.3', 'Up to 24h case battery', 'Touch controls', 'Low-latency mode'] },
  { id: 4, name: 'PulseBeat Mini Speaker', category: 'Audio', price: 999, oldPrice: 1399, badge: 'New', rating: 4.5, reviews: 67, image: 'images/product-04.svg', description: 'Portable Bluetooth speaker with punchy audio for rooms, desks and trips.', features: ['Bluetooth 5.2', '10h playback', 'USB-C charging', 'Compact body'] },
  { id: 5, name: 'Glide Pro Wireless Mouse', category: 'Computer', price: 649, oldPrice: 899, badge: 'Deal', rating: 4.6, reviews: 153, image: 'images/product-05.svg', description: 'Smooth wireless mouse with comfortable grip for work and study.', features: ['2.4GHz wireless', '1600 DPI', 'Silent clicks', 'Ergonomic shape'] },
  { id: 6, name: 'KeyLite Slim Keyboard', category: 'Computer', price: 899, oldPrice: 1199, badge: 'Popular', rating: 4.5, reviews: 101, image: 'images/product-06.svg', description: 'Low-profile wireless keyboard with a clean layout and quiet keys.', features: ['Wireless connection', 'Slim profile', 'Quiet typing', 'Long battery life'] },
  { id: 7, name: 'PowerHub 4-Port USB Hub', category: 'Computer', price: 749, oldPrice: 999, badge: '', rating: 4.4, reviews: 58, image: 'images/product-07.svg', description: 'Expand your laptop with four handy USB ports in a compact aluminium-style body.', features: ['4 USB ports', 'Plug and play', 'Compact design', 'USB 3.0 ready'] },
  { id: 8, name: 'ChargeDock 3-in-1 Stand', category: 'Mobile Accessories', price: 1499, oldPrice: 1999, badge: 'New', rating: 4.7, reviews: 44, image: 'images/product-08.svg', description: 'Desk-friendly charging stand for a cleaner, more organised setup.', features: ['3-device layout', 'Anti-slip base', 'Foldable design', 'Cable management'] },
  { id: 9, name: 'ShieldGlass 9H Screen Protector', category: 'Mobile Accessories', price: 199, oldPrice: 299, badge: 'Deal', rating: 4.5, reviews: 188, image: 'images/product-09.svg', description: 'Clear 9H tempered glass protection for everyday screen defence.', features: ['9H hardness', 'HD clarity', 'Oleophobic coating', 'Easy installation'] },
  { id: 10, name: 'SnapGrip Phone Stand', category: 'Mobile Accessories', price: 349, oldPrice: 499, badge: '', rating: 4.4, reviews: 73, image: 'images/product-10.svg', description: 'Adjustable desktop phone stand for calls, videos and hands-free use.', features: ['Adjustable angle', 'Foldable', 'Stable base', 'Desk friendly'] },
  { id: 11, name: 'PowerMax 10000mAh Bank', category: 'Power', price: 1099, oldPrice: 1499, badge: 'Best Seller', rating: 4.8, reviews: 241, image: 'images/product-11.svg', description: 'Slim 10000mAh power bank for reliable charging on the move.', features: ['10000mAh capacity', 'Dual output', 'USB-C input', 'LED indicator'] },
  { id: 12, name: 'TravelCharge 65W Adapter', category: 'Power', price: 1999, oldPrice: 2499, badge: 'Premium', rating: 4.7, reviews: 39, image: 'images/product-12.svg', description: 'High-output GaN-style travel adapter for phones, tablets and compatible laptops.', features: ['65W output', 'USB-C + USB-A', 'Compact body', 'Multi-device charging'] },
  { id: 13, name: 'CamGuard Full HD Webcam', category: 'Computer', price: 1299, oldPrice: 1699, badge: '', rating: 4.5, reviews: 52, image: 'images/product-13.svg', description: 'Simple Full HD webcam for video calls, classes and streaming.', features: ['1080p video', 'Built-in mic', 'USB plug and play', 'Clip mount'] },
  { id: 14, name: 'CoolPad Laptop Stand', category: 'Computer', price: 799, oldPrice: 1099, badge: 'Deal', rating: 4.6, reviews: 91, image: 'images/product-14.svg', description: 'Foldable aluminium-style laptop stand that raises your screen for a better desk setup.', features: ['Foldable', 'Adjustable height', 'Anti-slip pads', 'Portable'] },
  { id: 15, name: 'LinkPro USB-C Multi Adapter', category: 'Computer', price: 1599, oldPrice: 1999, badge: 'Popular', rating: 4.6, reviews: 76, image: 'images/product-15.svg', description: 'Multi-port adapter for modern laptops and tablets with USB-C connectivity.', features: ['HDMI output', 'USB ports', 'SD card support', 'USB-C pass-through'] },
  { id: 16, name: 'SmartTime Fit Watch', category: 'Smart Gadgets', price: 2499, oldPrice: 2999, badge: 'New', rating: 4.4, reviews: 63, image: 'images/product-16.svg', description: 'Everyday smart watch with a bright display and useful phone-connected features.', features: ['Colour display', 'Activity tracking', 'Call notifications', 'Multiple watch faces'] },
  { id: 17, name: 'NightGlow LED Desk Lamp', category: 'Smart Gadgets', price: 899, oldPrice: 1199, badge: '', rating: 4.5, reviews: 47, image: 'images/product-17.svg', description: 'Minimal LED desk lamp for focused work, study and late-night setups.', features: ['Touch controls', 'Adjustable brightness', 'USB power', 'Modern design'] },
  { id: 18, name: 'AirFlow USB Mini Fan', category: 'Daily Gadgets', price: 499, oldPrice: 699, badge: 'Deal', rating: 4.3, reviews: 84, image: 'images/product-18.svg', description: 'Compact USB-powered desk fan for personal airflow at home or work.', features: ['USB powered', 'Quiet motor', '3 speed levels', 'Compact size'] },
  { id: 19, name: 'CleanKey Keyboard Brush', category: 'Daily Gadgets', price: 149, oldPrice: 249, badge: '', rating: 4.2, reviews: 116, image: 'images/product-19.svg', description: 'Handy cleaning brush for keyboards, desks and small electronic surfaces.', features: ['Soft bristles', 'Compact', 'Reusable', 'Easy storage'] },
  { id: 20, name: 'CableMate Organiser Kit', category: 'Daily Gadgets', price: 299, oldPrice: 399, badge: 'Value', rating: 4.6, reviews: 139, image: 'images/product-20.svg', description: 'Keep charging and data cables neat with a practical organiser set.', features: ['Multiple pieces', 'Reusable', 'Flexible fit', 'Desk friendly'] },
  { id: 21, name: 'SoundCore AUX Adapter', category: 'Audio', price: 399, oldPrice: 599, badge: '', rating: 4.4, reviews: 48, image: 'images/product-21.svg', description: 'Compact audio adapter for compatible phones, cars and headphones.', features: ['Compact build', 'Clear audio', 'Plug and play', 'Travel friendly'] },
  { id: 22, name: 'GamePad X Wireless Controller', category: 'Gaming', price: 1899, oldPrice: 2299, badge: 'Popular', rating: 4.6, reviews: 72, image: 'images/product-22.svg', description: 'Comfortable wireless controller for compatible PC and gaming setups.', features: ['Wireless mode', 'Dual analogue sticks', 'Ergonomic grip', 'USB charging'] },
  { id: 23, name: 'USB Drive 64GB Metal', category: 'Storage', price: 549, oldPrice: 749, badge: 'Deal', rating: 4.5, reviews: 129, image: 'images/product-23.svg', description: 'Pocket-sized 64GB USB drive with a durable metal-style shell.', features: ['64GB capacity', 'USB connectivity', 'Compact', 'Protective cap'] },
  { id: 24, name: 'SecureCam Indoor Wi-Fi Camera', category: 'Smart Gadgets', price: 2199, oldPrice: 2799, badge: 'New', rating: 4.4, reviews: 35, image: 'images/product-24.svg', description: 'Compact indoor camera for everyday home monitoring with app connectivity.', features: ['Full HD video', 'Motion alerts', 'Night vision', 'Wi-Fi setup'] }
];
